packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - eslint@10.7.0
  - '@aws-sdk/client-s3@3.1091.0'
  - '@aws-sdk/s3-presigned-post@3.1091.0'
  - '@aws-sdk/s3-request-presigner@3.1091.0'

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  sharp: true
